HF-ADS7952 Driver: ads7952::ADS7952< SpiType > Class Template Reference
ads7952::ADS7952< SpiType > Class Template Reference
Main driver class for the ADS7952 ADC.
#include <ads7952.hpp>
Public Member Functions
ADS7952 (SpiType &spi, float vref=ADS7952_CFG::DEFAULT_VREF, float va=ADS7952_CFG::DEFAULT_VA) noexcept
Construct a new ADS7952 driver instance.
ADS7952 (const ADS7952 &)=delete
ADS7952 & operator= (const ADS7952 &)=delete
bool EnsureInitialized (bool force=false) noexcept
Ensure the driver is initialized — idempotent, safe to call repeatedly.
bool IsInitialized () const noexcept
Check if the driver has been initialized.
ReadResult ReadChannel (uint8_t channel) noexcept
Read a single ADC channel (switches to Manual mode).
ChannelReadings ReadAllChannels () noexcept
Read all channels in the current Auto-1 sequence.
float CountToVoltage (uint16_t count) const noexcept
Convert raw count to voltage using the currently active reference.
uint16_t VoltageToCount (float voltage) const noexcept
Convert a voltage to a 12-bit ADC count using the active reference.
bool EnterManualMode (uint8_t channel=0) noexcept
Enter Manual mode, selecting the given channel for conversion.
bool EnterAuto1Mode (bool reset_counter=true) noexcept
Enter Auto-1 mode (sequences through programmed channel mask).
bool EnterAuto2Mode (bool reset_counter=true) noexcept
Enter Auto-2 mode (sequences channels 0 through last_channel).
Mode GetMode () const noexcept
Get the current operating mode.
bool ProgramAuto1Channels (uint16_t channel_mask) noexcept
Program the Auto-1 channel sequence.
bool ProgramAuto2LastChannel (uint8_t last_channel) noexcept
Program the Auto-2 last channel.
bool ProgramGPIO (const GPIOConfig &config) noexcept
Program GPIO pin functions, direction, and alarm routing.
bool ProgramAlarm (uint8_t channel, AlarmBound bound, uint16_t threshold_12bit) noexcept
Program an alarm threshold for a single channel (count-based).
bool ProgramAlarmVoltage (uint8_t channel, AlarmBound bound, float voltage) noexcept
Program an alarm threshold for a single channel (voltage-based).
bool SetRange (Range range) noexcept
Set the input voltage range and update active reference.
Range GetRange () const noexcept
Get the current input range setting.
bool SetPowerDown (PowerDown pd) noexcept
Set the power-down mode.
void SetGPIOOutputs (uint8_t gpio_state) noexcept
Set GPIO output pin levels (for pins configured as outputs).
float GetVref () const noexcept
Get the configured reference voltage (Vref).
float GetActiveVref () const noexcept
Get the active voltage reference (affected by range setting).
uint16_t GetAuto1ChannelMask () const noexcept
Get the Auto-1 programmed channel mask. Bit ordering: bit N = channel N (bit 0 = CH0, bit 11 = CH11).
uint8_t GetAuto2LastChannel () const noexcept
Get the Auto-2 programmed last channel.
Static Public Member Functions
static constexpr float CountToVoltage (uint16_t count, float vref) noexcept
Convert raw count to voltage with explicit reference.
static constexpr uint8_t GetDriverVersionMajor () noexcept
static constexpr uint8_t GetDriverVersionMinor () noexcept
static constexpr uint8_t GetDriverVersionPatch () noexcept
Detailed Description
template<typename SpiType>
class ads7952::ADS7952< SpiType >
Main driver class for the ADS7952 ADC.
Template Parameters
SpiType Platform-specific SPI class derived from SpiInterface<SpiType>
Definition at line 58 of file ads7952.hpp.
Constructor & Destructor Documentation
ADS7952() [1/2]
template<typename SpiType > ads7952::ADS7952< SpiType >::ADS7952 (SpiType & spi, float vref = ADS7952_CFG::DEFAULT_VREF, float va = ADS7952_CFG::DEFAULT_VA) explicit noexcept
Construct a new ADS7952 driver instance.
Parameters
spi Reference to platform-specific SPI interface
vref REFP pin voltage in volts (default 2.5V for REF5025)
va VA supply voltage in volts (default 5.0V)
Definition at line 25 of file ads7952.ipp.
ADS7952() [2/2]
template<typename SpiType > ads7952::ADS7952< SpiType >::ADS7952 (const ADS7952< SpiType > &) delete
Member Function Documentation
CountToVoltage() [1/2]
template<typename SpiType > float ads7952::ADS7952< SpiType >::CountToVoltage (uint16_t count) const noexcept
Convert raw count to voltage using the currently active reference.
Parameters
count Raw 12-bit ADC count (0-4095)
Returns
Voltage in volts
Definition at line 163 of file ads7952.ipp.
References ads7952::reg::MAX_COUNT.
CountToVoltage() [2/2]
template<typename SpiType > static constexpr float ads7952::ADS7952< SpiType >::CountToVoltage (uint16_t count, float vref) inline static constexpr noexcept
Convert raw count to voltage with explicit reference.
Parameters
count Raw 12-bit ADC count (0-4095)
vref Reference voltage in volts
Returns
Voltage in volts
Definition at line 137 of file ads7952.hpp.
References ads7952::reg::MAX_COUNT.
EnsureInitialized()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::EnsureInitialized (bool force = false) noexcept
Ensure the driver is initialized — idempotent, safe to call repeatedly.
On first call: discards the invalid power-up conversion, programs defaults (Auto-1 channels, Auto-2 last channel), and enters Auto-1 mode. On subsequent calls: returns true immediately without SPI traffic.
Parameters
force If true, re-runs the full initialization sequence even if the driver is already initialized. Use after a device reset or power cycle.
Returns
true if the driver is initialized after the call
Definition at line 37 of file ads7952.ipp.
EnterAuto1Mode()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::EnterAuto1Mode (bool reset_counter = true) noexcept
Enter Auto-1 mode (sequences through programmed channel mask).
Parameters
reset_counter true to reset channel counter to start of sequence
Returns
true on success
Definition at line 192 of file ads7952.ipp.
References ads7952::Auto1, ads7952::reg::Mode::AUTO_1, ads7952::reg::NO_RESET_COUNTER, ads7952::reg::PROGRAM_ENABLE, and ads7952::reg::RESET_COUNTER.
EnterAuto2Mode()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::EnterAuto2Mode (bool reset_counter = true) noexcept
Enter Auto-2 mode (sequences channels 0 through last_channel).
Parameters
reset_counter true to reset channel counter to channel 0
Returns
true on success
Definition at line 202 of file ads7952.ipp.
References ads7952::Auto2, ads7952::reg::Mode::AUTO_2, ads7952::reg::NO_RESET_COUNTER, ads7952::reg::PROGRAM_ENABLE, and ads7952::reg::RESET_COUNTER.
EnterManualMode()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::EnterManualMode (uint8_t channel = 0) noexcept
Enter Manual mode, selecting the given channel for conversion.
Parameters
channel Channel to select (0-11, default 0)
Returns
true on success
Definition at line 181 of file ads7952.ipp.
References ads7952::reg::ChannelSelect(), ads7952::reg::Mode::MANUAL, ads7952::Manual, ads7952::reg::NUM_CHANNELS, and ads7952::reg::PROGRAM_ENABLE.
GetActiveVref()
template<typename SpiType > float ads7952::ADS7952< SpiType >::GetActiveVref () const inline noexcept
Get the active voltage reference (affected by range setting).
Definition at line 331 of file ads7952.hpp.
GetAuto1ChannelMask()
template<typename SpiType > uint16_t ads7952::ADS7952< SpiType >::GetAuto1ChannelMask () const inline noexcept
Get the Auto-1 programmed channel mask. Bit ordering: bit N = channel N (bit 0 = CH0, bit 11 = CH11).
Definition at line 335 of file ads7952.hpp.
GetAuto2LastChannel()
template<typename SpiType > uint8_t ads7952::ADS7952< SpiType >::GetAuto2LastChannel () const inline noexcept
Get the Auto-2 programmed last channel.
Definition at line 338 of file ads7952.hpp.
GetDriverVersionMajor()
template<typename SpiType > static constexpr uint8_t ads7952::ADS7952< SpiType >::GetDriverVersionMajor () inline static constexpr noexcept
Definition at line 343 of file ads7952.hpp.
GetDriverVersionMinor()
template<typename SpiType > static constexpr uint8_t ads7952::ADS7952< SpiType >::GetDriverVersionMinor () inline static constexpr noexcept
Definition at line 344 of file ads7952.hpp.
GetDriverVersionPatch()
template<typename SpiType > static constexpr uint8_t ads7952::ADS7952< SpiType >::GetDriverVersionPatch () inline static constexpr noexcept
Definition at line 345 of file ads7952.hpp.
GetMode()
template<typename SpiType > Mode ads7952::ADS7952< SpiType >::GetMode () const inline noexcept
Get the current operating mode.
Definition at line 178 of file ads7952.hpp.
GetRange()
template<typename SpiType > Range ads7952::ADS7952< SpiType >::GetRange () const inline noexcept
Get the current input range setting.
Definition at line 296 of file ads7952.hpp.
GetVref()
template<typename SpiType > float ads7952::ADS7952< SpiType >::GetVref () const inline noexcept
Get the configured reference voltage (Vref).
Definition at line 328 of file ads7952.hpp.
IsInitialized()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::IsInitialized () const inline noexcept
Check if the driver has been initialized.
Definition at line 97 of file ads7952.hpp.
operator=()
template<typename SpiType > ADS7952 & ads7952::ADS7952< SpiType >::operator= (const ADS7952< SpiType > &) delete
ProgramAlarm()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::ProgramAlarm (uint8_t channel, AlarmBound bound, uint16_t threshold_12bit) noexcept
Program an alarm threshold for a single channel (count-based).
The 12-bit ADC count (0–4095) is internally truncated to 10 bits for the hardware alarm register (only the top 10 bits are stored).
Parameters
channel Channel number (0–11)
bound Low or High alarm threshold
threshold_12bit 12-bit ADC count (0–4095); internally right-shifted by 2 to produce 10-bit hardware threshold
Returns
true on success
adc.ProgramAlarm(0, ads7952::AlarmBound::High, 3000);  // Raw count
Definition at line 296 of file ads7952.ipp.
References ads7952::reg::Mode::ALARM_GROUP_0, ads7952::reg::Mode::ALARM_GROUP_1, ads7952::reg::Mode::ALARM_GROUP_2, ads7952::reg::Alarm::ChannelInGroup(), ads7952::reg::CHANNELS_PER_ALARM_GROUP, ads7952::reg::Mode::CONTINUE, ads7952::reg::Alarm::EXIT_NEXT_FRAME, ads7952::High, ads7952::reg::Alarm::HIGH_REGISTER, ads7952::reg::NUM_CHANNELS, and ads7952::reg::Alarm::Threshold12To10().
ProgramAlarmVoltage()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::ProgramAlarmVoltage (uint8_t channel, AlarmBound bound, float voltage) noexcept
Program an alarm threshold for a single channel (voltage-based).
Converts the voltage to a 12-bit count using the currently active reference voltage, then programs the hardware alarm register.
Warning
The hardware alarm register stores a raw count, not a voltage. If the range is later changed via SetRange(), the stored count will correspond to a different physical voltage and the alarm will trigger at the wrong level. Re-call ProgramAlarmVoltage() after any SetRange() call to re-synchronize.
Parameters
channel Channel number (0–11)
bound Low or High alarm threshold
voltage Threshold voltage in volts (clamped to valid range)
Returns
true on success
adc.ProgramAlarmVoltage(0, ads7952::AlarmBound::Low,  0.5f);
adc.ProgramAlarmVoltage(0, ads7952::AlarmBound::High, 2.0f);
// After a range change, re-program to restore correct thresholds:
adc.SetRange(ads7952::Range::TwoVref);
adc.ProgramAlarmVoltage(0, ads7952::AlarmBound::Low,  0.5f);  // re-sync
adc.ProgramAlarmVoltage(0, ads7952::AlarmBound::High, 2.0f);  // re-sync
Definition at line 336 of file ads7952.ipp.
References ads7952::VoltageToCount().
ProgramAuto1Channels()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::ProgramAuto1Channels (uint16_t channel_mask) noexcept
Program the Auto-1 channel sequence.
Bit ordering: bit N enables channel N (bit 0 = CH0, bit 11 = CH11, LSB-first). Only bits [11:0] are used; upper bits are masked off.
Use the ads7952::ChannelMask() helper or predefined constants:
adc.ProgramAuto1Channels(ads7952::ChannelMask(0, 2, 4));  // CH0, CH2, CH4
adc.ProgramAuto1Channels(ads7952::kAllChannels);           // All 12
adc.ProgramAuto1Channels(ads7952::kEvenChannels);          // Even only
adc.ProgramAuto1Channels(ads7952::ChannelRangeMask(0, 5)); // CH0–CH5
Parameters
channel_mask Bitmask where bit N enables channel N (bits [11:0])
Returns
true on success
Definition at line 216 of file ads7952.ipp.
References ads7952::reg::Mode::AUTO_1_PROG.
ProgramAuto2LastChannel()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::ProgramAuto2LastChannel (uint8_t last_channel) noexcept
Program the Auto-2 last channel.
Parameters
last_channel Last channel in sequence (0-11)
Returns
true on success
Definition at line 233 of file ads7952.ipp.
References ads7952::reg::Auto2LastChannel(), ads7952::reg::Mode::AUTO_2_PROG, and ads7952::reg::NUM_CHANNELS.
ProgramGPIO()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::ProgramGPIO (const GPIOConfig & config) noexcept
Program GPIO pin functions, direction, and alarm routing.
Configures which GPIO pins act as inputs or outputs, assigns alarm signalling roles to GPIO0/GPIO1, optionally assigns GPIO2/GPIO3 as hardware range/power-down inputs, and optionally resets all device registers. Sends a single GPIO_PROG mode frame.
Parameters
config GPIO configuration structure
Returns
true on success
Definition at line 248 of file ads7952.ipp.
References ads7952::GPIO, ads7952::reg::GPIOProg::GPIO0_HI_ALARM, ads7952::reg::GPIOProg::GPIO0_HI_LO_ALARM, ads7952::GPIO0_HighAlarm, ads7952::GPIO0_HighAndLowAlarm, ads7952::reg::GPIOProg::GPIO1_HI_ALARM, ads7952::GPIO1_HighAlarm, ads7952::reg::GPIOProg::GPIO1_LO_GPIO0_HI_ALARM, ads7952::GPIO1_LowAlarm_GPIO0_HighAlarm, ads7952::reg::GPIOProg::GPIO2_RANGE_IN, ads7952::reg::GPIOProg::GPIO3_PWRDOWN_IN, ads7952::reg::Mode::GPIO_PROG, and ads7952::reg::GPIOProg::RESET_ALL_REGS.
ReadAllChannels()
template<typename SpiType > ChannelReadings ads7952::ADS7952< SpiType >::ReadAllChannels () noexcept
Read all channels in the current Auto-1 sequence.
Enters Auto-1 mode with channel counter reset and reads until all programmed channels are received or timeout.
Returns
ChannelReadings with per-channel counts and voltages
Definition at line 107 of file ads7952.ipp.
References ads7952::Auto1, ads7952::reg::Mode::AUTO_1, ads7952::reg::Mode::CONTINUE, ads7952::ChannelReadings::error, ads7952::reg::Response::GetChannel(), ads7952::reg::Response::GetData(), ads7952::ChannelReadings::MAX_CHANNELS, ads7952::NotInitialized, ads7952::Ok, ads7952::reg::PROGRAM_RETAIN, ADS7952_CFG::READ_ALL_MAX_EXTRA_FRAMES, ads7952::reg::RESET_COUNTER, and ads7952::Timeout.
ReadChannel()
template<typename SpiType > ReadResult ads7952::ADS7952< SpiType >::ReadChannel (uint8_t channel) noexcept
Read a single ADC channel (switches to Manual mode).
Parameters
channel Channel number (0-11)
Returns
ReadResult with count, voltage, channel, and error status
Definition at line 74 of file ads7952.ipp.
References ads7952::reg::ChannelSelect(), ads7952::reg::Mode::CONTINUE, ads7952::ReadResult::error, ads7952::reg::Response::GetChannel(), ads7952::reg::Response::GetData(), ads7952::InvalidChannel, ads7952::reg::Mode::MANUAL, ads7952::Manual, ads7952::NotInitialized, ads7952::reg::NUM_CHANNELS, ads7952::Ok, and ads7952::reg::PROGRAM_RETAIN.
SetGPIOOutputs()
template<typename SpiType > void ads7952::ADS7952< SpiType >::SetGPIOOutputs (uint8_t gpio_state) noexcept
Set GPIO output pin levels (for pins configured as outputs).
Bit ordering: bit N controls GPIO pin N (bit 0 = GPIO0, bit 3 = GPIO3). 1 = high, 0 = low. Use ads7952::gpio:: constants:
adc.SetGPIOOutputs(ads7952::gpio::kGPIO2 | ads7952::gpio::kGPIO3);
adc.SetGPIOOutputs(ads7952::gpio::kNone);  // All low
Parameters
gpio_state Bits [3:0] — 1 = high, 0 = low per pin
Definition at line 373 of file ads7952.ipp.
References ads7952::reg::Mode::CONTINUE.
SetPowerDown()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::SetPowerDown (PowerDown pd) noexcept
Set the power-down mode.
Parameters
pd Normal or PowerDown
Returns
true on success
Definition at line 359 of file ads7952.ipp.
References ads7952::reg::Mode::CONTINUE.
SetRange()
template<typename SpiType > bool ads7952::ADS7952< SpiType >::SetRange (Range range) noexcept
Set the input voltage range and update active reference.
Changes the hardware reference voltage used for SAR conversions by sending a CONTINUE frame with the updated range bit. Also updates the internal active_vref_ used by CountToVoltage() and VoltageToCount().
Warning
Alarm thresholds are stored in the hardware as raw counts. Changing the range changes the count produced for any given physical voltage, so existing alarm thresholds will fire at different voltages after a range change. If alarms were programmed using ProgramAlarmVoltage(), re-call it after SetRange() to correct the hardware registers.
Parameters
range Vref or TwoVref
Returns
true on success
Definition at line 346 of file ads7952.ipp.
References ads7952::reg::Mode::CONTINUE, and ads7952::TwoVref.
VoltageToCount()
template<typename SpiType > uint16_t ads7952::ADS7952< SpiType >::VoltageToCount (float voltage) const noexcept
Convert a voltage to a 12-bit ADC count using the active reference.
Instance version — uses the currently active reference voltage (affected by the Range setting). Result is clamped to 0–4095.
Parameters
voltage Target voltage in volts
Returns
12-bit ADC count (0–4095)
Definition at line 169 of file ads7952.ipp.
References ads7952::reg::MAX_COUNT.
The documentation for this class was generated from the following files:
inc/ads7952.hpp
src/ads7952.ipp